/** @type {import('tailwindcss').Config} */
import forms from "@tailwindcss/forms";

export default {
  darkMode: "class",
  content: [],
  theme: {
    extend: {
      colors: {
        background: "#fbf8ff",
        surface: "#fbf8ff",
        "surface-bright": "#fbf8ff",
        "surface-dim": "#dad9e3",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f2fc",
        "surface-container": "#eeedf7",
        "surface-container-high": "#e8e7f1",
        "surface-container-highest": "#e3e1eb",
        "surface-variant": "#e3e1eb",
        "on-surface": "#1a1b22",
        "on-background": "#1a1b22",
        "on-surface-variant": "#444653",
        "inverse-surface": "#2f3037",
        "inverse-on-surface": "#f1f0fa",
        outline: "#757684",
        "outline-variant": "#c4c5d5",
        "surface-tint": "#3755c3",
        primary: "#00288e",
        "on-primary": "#ffffff",
        "primary-container": "#1e40af",
        "on-primary-container": "#a8b8ff",
        "primary-light": "#eff6ff",
        "inverse-primary": "#b8c4ff",
        "primary-fixed": "#dde1ff",
        "primary-fixed-dim": "#b8c4ff",
        "on-primary-fixed": "#001453",
        "on-primary-fixed-variant": "#173bab",
        secondary: "#505f76",
        "on-secondary": "#ffffff",
        "secondary-container": "#d0e1fb",
        "on-secondary-container": "#54647a",
        "secondary-fixed": "#d3e4fe",
        "secondary-fixed-dim": "#b7c8e1",
        "on-secondary-fixed": "#0b1c30",
        "on-secondary-fixed-variant": "#38485d",
        tertiary: "#611e00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#872d00",
        "on-tertiary-container": "#ffa583",
        "tertiary-fixed": "#ffdbce",
        "tertiary-fixed-dim": "#ffb59a",
        "on-tertiary-fixed": "#380d00",
        "on-tertiary-fixed-variant": "#802a00",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        success: "#10b981",
        warning: "#f59e0b",
        "bg-main": "#f8fafc",
        border: "#e2e8f0",
        "text-main": "#0f172a",
        "text-muted": "#64748b",
        "text-light": "#94a3b8",
        "admin-bg": "#06080A",
        "admin-card": "#161A26",
        "admin-surface": "#1C1F2E",
        "admin-text": "#F1F5F9",
        brand: {
          50: "#eff6ff",
          100: "#dbeafe",
          200: "#bfdbfe",
          300: "#93c5fd",
          400: "#60a5fa",
          500: "#3b82f6",
          600: "#2563eb",
          700: "#1d4ed8",
          800: "#1e40af",
          900: "#1e3a8a",
          950: "#172554",
        },
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        h1: ["Inter", "sans-serif"],
        h2: ["Inter", "sans-serif"],
        h3: ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        code: ["monospace"],
      },
      fontSize: {
        h1: ["36px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        h2: ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        h3: ["18px", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        card: "20px",
        btn: "12px",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        gutter: "24px",
        margin: "48px",
        "sidebar-width": "280px",
        "header-height": "80px",
        "mentor-sidebar": "256px",
        "mentor-header": "64px",
        "admin-sidebar": "260px",
        "admin-header": "64px",
      },
      boxShadow: {
        card: "0 4px 6px -1px rgba(0,0,0,0.05)",
        sidebar: "20px 0 50px rgba(0,0,0,0.1)",
        login: "0 10px 25px rgba(0,0,0,0.05)",
      },
    },
  },
  plugins: [forms],
};
